// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderAccumulator.Infrastructure.Persistence;

#nullable disable

namespace OrderAccumulator.Infrastructure.Migrations
{
    [DbContext(typeof(OrderAccumulatorDbContext))]
    [Migration("20260929053143_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderAccumulator.Infrastructure.Persistence.Tabelas.ExposicaoRow", b =>
                {
                    b.Property<string>("Ativo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ativo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Ativo");

                    b.ToTable("exposicoes", (string)null);

                    b.HasData(
                        new
                        {
                            Ativo = "PETR4",
                            Valor = 0m
                        },
                        new
                        {
                            Ativo = "VALE3",
                            Valor = 0m
                        },
                        new
                        {
                            Ativo = "VIIA4",
                            Valor = 0m
                        });
                });

            modelBuilder.Entity("OrderAccumulator.Infrastructure.Persistence.Tabelas.OrdemAceitaRow", b =>
                {
                    b.Property<Guid>("OrdemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_id");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ativo");

                    b.Property<decimal>("ExposicaoResultante")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("exposicao_resultante");

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("lado");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("OrdemId");

                    b.ToTable("ordens_aceitas", (string)null);
                });

            modelBuilder.Entity("OrderAccumulator.Infrastructure.Persistence.Tabelas.OutboxMensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chave");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset?>("PublicadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicada_em");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CriadaEm")
                        .HasFilter("publicada_em IS NULL");

                    b.ToTable("outbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
